### ISSUE TITLE
"Bigger Pouch" Card Inconsistency

### ISSUE THREAD

**Issue by mtnbikegamer** [oliveman521/We-Wizards-Three#2]
The thing that adds five recourses only works 50% of the time.

**Comment by oliveman521** [comment]
Cannot reproduce either in current project or in release 0.6.0.

**Comment by oliveman521** [comment]
Bug was due to the code that checks for passive abilities accidentally clearing one-off abilities on every check, rather than only on checks that are met. Fixed in 0.6.3
